### ISSUE TITLE
move to another raspi

### ISSUE THREAD

**Issue by h4nc** [ycardon/gigaset-elements-proxy#9]
I'd like to move the gigaset proxy to another pi. 

I installed everything as before and unplugged the old pi, but I get an error within the new install.

I have to mention that at this new Pi I rund "pihole". Could both services disturb each other?

This is the log:

> Jän 15 10:18:52 raspberrypi systemd[1]: Stopped GigasetElements Server (local proxy to gigaset APIs).
> Jän 15 10:18:52 raspberrypi systemd[1]: Started GigasetElements Server (local proxy to gigaset APIs).
> Jän 15 10:19:04 raspberrypi node[882]: [Tue Jan 15 2019 10:19:04] [INFO]   gigaset-element-provy v1.4.2 starting
> Jän 15 10:19:12 raspberrypi node[882]: events.js:183
> Jän 15 10:19:12 raspberrypi node[882]:       throw er; // Unhandled 'error' event
> Jän 15 10:19:12 raspberrypi systemd[1]: gigaset-server@pi.service: Main process exited, code=exited, status=1/FAILURE
> Jän 15 10:19:12 raspberrypi systemd[1]: gigaset-server@pi.service: Unit entered failed state.
> Jän 15 10:19:12 raspberrypi systemd[1]: gigaset-server@pi.service: Failed with result 'exit-code'.
> Jän 15 10:19:22 raspberrypi systemd[1]: gigaset-server@pi.service: Service hold-off time over, scheduling restart.
> Jän 15 10:19:22 raspberrypi systemd[1]: Stopped GigasetElements Server (local proxy to gigaset APIs).
> Jän 15 10:19:22 raspberrypi systemd[1]: Started GigasetElements Server (local proxy to gigaset APIs).

**Comment by ycardon** [comment]
Hi, to debug you could try to run the program standalone, not as a service: ``cd <my_install_dir>`` then ``node app.js``

What could fail:
- adress and credential of mqtt broker
- credentials of Gigaset account
- ...

**Comment by h4nc** [comment]
This is the error I get running it standalone:

```
[Tue Jan 15 2019 14:56:30] [INFO]   gigaset-element-provy v1.4.2 starting
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/home/pi/gigaset-elements-proxy/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/home/pi/gigaset-elements-proxy/node_modules/mqtt/lib/client.js:350:12)
    at work (/home/pi/gigaset-elements-proxy/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/home/pi/gigaset-elements-proxy/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/home/pi/gigaset-elements-proxy/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/pi/gigaset-elements-proxy/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/home/pi/gigaset-elements-proxy/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
```

You probably wondering why the hell does he chance a running system. Currently I have it running on  a pi zero (wifi) and I got a cheap raspi 3B+ and I wand to speed everything up a little using the ethernet port of the 3B+.
